blank_issues_enabled: false
contact_links:
  - name: DotNetEvolution Discord Server
    url: https://aka.ms/dotnet-discord
    about: Please ask and answer questions here in the #xamarin-community-toolkit channel.
