//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.CommunityToolkit.Sample.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.CommunityToolkit.Sample.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string CameraViewTitle {
            get {
                return ResourceManager.GetString("CameraViewTitle", resourceCulture);
            }
        }
        
        internal static string CameraViewDescription {
            get {
                return ResourceManager.GetString("CameraViewDescription", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleZoom {
            get {
                return ResourceManager.GetString("CameraViewSampleZoom", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleSnapPicture {
            get {
                return ResourceManager.GetString("CameraViewSampleSnapPicture", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleStartRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStartRecording", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleStopRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStopRecording", resourceCulture);
            }
        }
        
        internal static string RequiredStringValidationDescription {
            get {
                return ResourceManager.GetString("RequiredStringValidationDescription", resourceCulture);
            }
        }
        
        internal static string RequiredStringValidationShortDescription {
            get {
                return ResourceManager.GetString("RequiredStringValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string PasswordMatched {
            get {
                return ResourceManager.GetString("PasswordMatched", resourceCulture);
            }
        }
        
        internal static string DateTimeOffsetConverterShortDescription {
            get {
                return ResourceManager.GetString("DateTimeOffsetConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string ExpanderTitle {
            get {
                return ResourceManager.GetString("ExpanderTitle", resourceCulture);
            }
        }
        
        internal static string ExpanderDescription {
            get {
                return ResourceManager.GetString("ExpanderDescription", resourceCulture);
            }
        }
        
        internal static string NestedExpander {
            get {
                return ResourceManager.GetString("NestedExpander", resourceCulture);
            }
        }
        
        internal static string EnableNested {
            get {
                return ResourceManager.GetString("EnableNested", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorDescription {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorDescription", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorDismissKeyboardOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorDismissKeyboardOptionLabel", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorSearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorSearchBarPlaceholderText", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorSearchResultLabelFormat {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorSearchResultLabelFormat", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorShortDescription {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorShortDescription", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorTimeThresholdOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorTimeThresholdOptionLabel", resourceCulture);
            }
        }
        
        internal static string AutoGridLayoutBehaviorDescription {
            get {
                return ResourceManager.GetString("AutoGridLayoutBehaviorDescription", resourceCulture);
            }
        }
        
        internal static string ImpliedOrderGridDescriptionLabel {
            get {
                return ResourceManager.GetString("ImpliedOrderGridDescriptionLabel", resourceCulture);
            }
        }
        
        internal static string ShowSnackBarWithActionButton {
            get {
                return ResourceManager.GetString("ShowSnackBarWithActionButton", resourceCulture);
            }
        }
        
        internal static string ShieldTitle {
            get {
                return ResourceManager.GetString("ShieldTitle", resourceCulture);
            }
        }
        
        internal static string ShieldDescription {
            get {
                return ResourceManager.GetString("ShieldDescription", resourceCulture);
            }
        }
        
        internal static string ActionsPageDescription {
            get {
                return ResourceManager.GetString("ActionsPageDescription", resourceCulture);
            }
        }
        
        internal static string ActionsPageTitle {
            get {
                return ResourceManager.GetString("ActionsPageTitle", resourceCulture);
            }
        }
        
        internal static string ShowSnackBarNoActionButton {
            get {
                return ResourceManager.GetString("ShowSnackBarNoActionButton", resourceCulture);
            }
        }
        
        internal static string SnackBarIsClosedByTimeout {
            get {
                return ResourceManager.GetString("SnackBarIsClosedByTimeout", resourceCulture);
            }
        }
        
        internal static string SnackBarIsClosedByUser {
            get {
                return ResourceManager.GetString("SnackBarIsClosedByUser", resourceCulture);
            }
        }
        
        internal static string GravatarImageSourceDescription {
            get {
                return ResourceManager.GetString("GravatarImageSourceDescription", resourceCulture);
            }
        }
        
        internal static string GravatarImageSourceTitle {
            get {
                return ResourceManager.GetString("GravatarImageSourceTitle", resourceCulture);
            }
        }
        
        internal static string DefaultGravatar {
            get {
                return ResourceManager.GetString("DefaultGravatar", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string FullImageSource {
            get {
                return ResourceManager.GetString("FullImageSource", resourceCulture);
            }
        }
        
        internal static string GravatarSize {
            get {
                return ResourceManager.GetString("GravatarSize", resourceCulture);
            }
        }
        
        internal static string XAMLExtension {
            get {
                return ResourceManager.GetString("XAMLExtension", resourceCulture);
            }
        }
        
        internal static string UserStoppedTypingBehaviorMinimumLengthThresholdOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorMinimumLengthThresholdOptionLabel", resourceCulture);
            }
        }
        
        internal static string Effects_Description {
            get {
                return ResourceManager.GetString("Effects Description", resourceCulture);
            }
        }
        
        internal static string EffectsTitle {
            get {
                return ResourceManager.GetString("EffectsTitle", resourceCulture);
            }
        }
        
        internal static string SafeAreaShortDescription {
            get {
                return ResourceManager.GetString("SafeAreaShortDescription", resourceCulture);
            }
        }
        
        internal static string SafeAreaLongDescription {
            get {
                return ResourceManager.GetString("SafeAreaLongDescription", resourceCulture);
            }
        }
        
        internal static string ToggleSafeAreaEffect {
            get {
                return ResourceManager.GetString("ToggleSafeAreaEffect", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorShortDescription {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorShortDescription", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorCommandExecutionLabelFormat {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorCommandExecutionLabelFormat", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorDescription {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorDescription", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorDismissKeyboardOptionLabel {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorDismissKeyboardOptionLabel", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorEntryPlaceholder {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorFirstScenarioDescription {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorFirstScenarioDescription", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorMaxLengthSettingLabel {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorMaxLengthSettingLabel", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorNextEntryPlaceholder {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorNextEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string MaxLengthReachedBehaviorSecondScenarioDescription {
            get {
                return ResourceManager.GetString("MaxLengthReachedBehaviorSecondScenarioDescription", resourceCulture);
            }
        }

        internal static string ContentButtonTitle {
            get {
                return ResourceManager.GetString("ContentButtonTitle", resourceCulture);
            }
        }
        
        internal static string ContentButtonDescription {
            get {
                return ResourceManager.GetString("ContentButtonDescription", resourceCulture);
            }
        }
        
        internal static string ContentButtonTapDescription {
            get {
                return ResourceManager.GetString("ContentButtonTapDescription", resourceCulture);
            }
        }
        
        internal static string ContentButtonTapMessage {
            get {
                return ResourceManager.GetString("ContentButtonTapMessage", resourceCulture);
            }
        }
    }
}
