//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.CommunityToolkit.Sample.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.CommunityToolkit.Sample.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SnackBar, toast etc.
        /// </summary>
        internal static string ActionsPageDescription {
            get {
                return ResourceManager.GetString("ActionsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionsPageTitle {
            get {
                return ResourceManager.GetString("ActionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to use ViewTappedAnimationBehaviour applying it in different UI elements..
        /// </summary>
        internal static string AnimationBehaviorTitle {
            get {
                return ResourceManager.GetString("AnimationBehaviorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform animation when the specified UI element event is triggered..
        /// </summary>
        internal static string AnimatioShortDescription {
            get {
                return ResourceManager.GetString("AnimatioShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This behavior assigns grid row and column based on the order a view is added to the grid..
        /// </summary>
        internal static string AutoGridLayoutBehaviorDescription {
            get {
                return ResourceManager.GetString("AutoGridLayoutBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AvatarView represents a user&apos;s name by using the initials and a generated background color..
        /// </summary>
        internal static string AvatarViewDescription {
            get {
                return ResourceManager.GetString("AvatarViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Property:.
        /// </summary>
        internal static string AvatarViewSizeText {
            get {
                return ResourceManager.GetString("AvatarViewSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvatarView.
        /// </summary>
        internal static string AvatarViewTitle {
            get {
                return ResourceManager.GetString("AvatarViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors lets you add functionality to user interface controls without having to subclass them. Behaviors are written in code and added to controls in XAML or code..
        /// </summary>
        internal static string BehaviorsDescription {
            get {
                return ResourceManager.GetString("BehaviorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors.
        /// </summary>
        internal static string BehaviorsTitle {
            get {
                return ResourceManager.GetString("BehaviorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A converter that allows you to convert byte array to an object of a type ImageSource..
        /// </summary>
        internal static string ByteArrayToImageSourceShortDescription {
            get {
                return ResourceManager.GetString("ByteArrayToImageSourceShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CameraView allows you to show a live preview from the camera. You can take pictures, record videos and much more!.
        /// </summary>
        internal static string CameraViewDescription {
            get {
                return ResourceManager.GetString("CameraViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap Picture.
        /// </summary>
        internal static string CameraViewSampleSnapPicture {
            get {
                return ResourceManager.GetString("CameraViewSampleSnapPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string CameraViewSampleStartRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string CameraViewSampleStopRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: {0}.
        /// </summary>
        internal static string CameraViewSampleZoom {
            get {
                return ResourceManager.GetString("CameraViewSampleZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraView.
        /// </summary>
        internal static string CameraViewTitle {
            get {
                return ResourceManager.GetString("CameraViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        internal static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Thumbs Radius.
        /// </summary>
        internal static string ControlThumbsRadius {
            get {
                return ResourceManager.GetString("ControlThumbsRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Track Radius.
        /// </summary>
        internal static string ControlTrackRadius {
            get {
                return ResourceManager.GetString("ControlTrackRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters let you convert bindings of a certain type to a different value, based on custom logic..
        /// </summary>
        internal static string ConvertersDescription {
            get {
                return ResourceManager.GetString("ConvertersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters.
        /// </summary>
        internal static string ConvertersTitle {
            get {
                return ResourceManager.GetString("ConvertersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A converter that allows to convert from a DateTimeOffset type to a DateTime type..
        /// </summary>
        internal static string DateTimeOffsetConverterShortDescription {
            get {
                return ResourceManager.GetString("DateTimeOffsetConverterShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Gravatar.
        /// </summary>
        internal static string DefaultGravatar {
            get {
                return ResourceManager.GetString("DefaultGravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects are used to add visual customization on a control by control bases.
        /// </summary>
        internal static string Effects_Description {
            get {
                return ResourceManager.GetString("Effects Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        internal static string EffectsTitle {
            get {
                return ResourceManager.GetString("EffectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g..
        /// </summary>
        internal static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color will change accordingly to the style that is configured when a invalid value (email address) is entered..
        /// </summary>
        internal static string EmailValidationDescription {
            get {
                return ResourceManager.GetString("EmailValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes an Entry&apos;s text color when an invalid e-mail address is provided..
        /// </summary>
        internal static string EmailValidationShortDescription {
            get {
                return ResourceManager.GetString("EmailValidationShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable nested:.
        /// </summary>
        internal static string EnableNested {
            get {
                return ResourceManager.GetString("EnableNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to use EventToCommandBehavior. Here we observe Clicked event of the button and trigger IncrementCommand from ViewModel..
        /// </summary>
        internal static string EventToCommandBehaviorDescription {
            get {
                return ResourceManager.GetString("EventToCommandBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns any event into a command that can be bound to..
        /// </summary>
        internal static string EventToCommandShortDescription {
            get {
                return ResourceManager.GetString("EventToCommandShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xamarin.Forms Expander control provides an expandable container to host any content..
        /// </summary>
        internal static string ExpanderDescription {
            get {
                return ResourceManager.GetString("ExpanderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        internal static string ExpanderTitle {
            get {
                return ResourceManager.GetString("ExpanderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions are used to supplement existing functionalities by making them easier to use..
        /// </summary>
        internal static string ExtensionsDescription {
            get {
                return ResourceManager.GetString("ExtensionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string ExtensionsTitle {
            get {
                return ResourceManager.GetString("ExtensionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Image Source.
        /// </summary>
        internal static string FullImageSource {
            get {
                return ResourceManager.GetString("FullImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you XamarinCommunityToolkit contributors.
        /// </summary>
        internal static string GratitudeMessage {
            get {
                return ResourceManager.GetString("GratitudeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GravatarImageSource allows you to easily utilize a users Gravatar image from Gravatar.com using nothing but their email address..
        /// </summary>
        internal static string GravatarImageSourceDescription {
            get {
                return ResourceManager.GetString("GravatarImageSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GravatarImageSource.
        /// </summary>
        internal static string GravatarImageSourceTitle {
            get {
                return ResourceManager.GetString("GravatarImageSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GravatarSize.
        /// </summary>
        internal static string GravatarSize {
            get {
                return ResourceManager.GetString("GravatarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior that auto sets row and column assignments of child views by the order they are defined in the grid. RowSpan and ColumnSpan are honored during the auto-assignment of row and column.
        ///
        ///By default, if more cells in the grid are needed by the number of child views then are defined an output warning will be generated. If a row or column span exceeds the defined rows and columns output warnings will be generated.
        ///
        ///The user may at their choice decide to have output warnings treated as exceptions.
        ///
        ///If [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpliedOrderGridDescriptionLabel {
            get {
                return ResourceManager.GetString("ImpliedOrderGridDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xamarin Community Toolkit is a collection of Animations, Behaviors, Converters, and Effects for mobile development with Xamarin.Forms. It simplifies and demonstrates common developer tasks building iOS, Android, and UWP apps with Xamarin.Forms..
        /// </summary>
        internal static string IntroductionDescription {
            get {
                return ResourceManager.GetString("IntroductionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing the XamarinCommunityToolkit.
        /// </summary>
        internal static string IntroductionTitle {
            get {
                return ResourceManager.GetString("IntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Enabled.
        /// </summary>
        internal static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tapped.
        /// </summary>
        internal static string ItemTapped {
            get {
                return ResourceManager.GetString("ItemTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A converter that allows you to extract the value from ItemTappedEventArgs that can be used in combination with EventToCommandBehavior..
        /// </summary>
        internal static string ItemTappedEventArgsShortDescription {
            get {
                return ResourceManager.GetString("ItemTappedEventArgsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A converter that allows you to extract the value from ItemSelectedEventArgs that can be used in combination with EventToCommandBehavior..
        /// </summary>
        internal static string ItemTappedSelectedEventArgsShortDescription {
            get {
                return ResourceManager.GetString("ItemTappedSelectedEventArgsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        internal static string LoadingDataMessage {
            get {
                return ResourceManager.GetString("LoadingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Lower Thumb Border Color.
        /// </summary>
        internal static string LowerThumbBorderColor {
            get {
                return ResourceManager.GetString("LowerThumbBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Thumb Color.
        /// </summary>
        internal static string LowerThumbColor {
            get {
                return ResourceManager.GetString("LowerThumbColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Thumb Radius.
        /// </summary>
        internal static string LowerThumbRadius {
            get {
                return ResourceManager.GetString("LowerThumbRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Thumb Size.
        /// </summary>
        internal static string LowerThumbSize {
            get {
                return ResourceManager.GetString("LowerThumbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Thumb View Set.
        /// </summary>
        internal static string LowerThumbViewSet {
            get {
                return ResourceManager.GetString("LowerThumbViewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to use MaskedBehavior.
        /// </summary>
        internal static string MaskedDescription {
            get {
                return ResourceManager.GetString("MaskedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked text in entry with specific pattern.
        /// </summary>
        internal static string MaskedShortDescription {
            get {
                return ResourceManager.GetString("MaskedShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaElement is a view for playing video and audio..
        /// </summary>
        internal static string MediaElementDescription {
            get {
                return ResourceManager.GetString("MediaElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaElement.
        /// </summary>
        internal static string MediaElementTitle {
            get {
                return ResourceManager.GetString("MediaElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to use the MultiBinding Converter with the NotEqualConverter and the TextCaseConverter. 
        ///
        ///It converts the entered text to Upper Case and checks that it is Not Equal to the string &apos;ANDREI&apos;..
        /// </summary>
        internal static string MultiConverterDescription {
            get {
                return ResourceManager.GetString("MultiConverterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates how to use Multibinding Converter.
        /// </summary>
        internal static string MultiConverterShortDescription {
            get {
                return ResourceManager.GetString("MultiConverterShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color will change accordingly to the style that is configured if any of child behaviors is invalid (Minimum: -10, Maximum: 5)..
        /// </summary>
        internal static string MultiValidationDescription {
            get {
                return ResourceManager.GetString("MultiValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combines multiple validation behavior..
        /// </summary>
        internal static string MultiValidationShortDescription {
            get {
                return ResourceManager.GetString("MultiValidationShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested expander.
        /// </summary>
        internal static string NestedExpander {
            get {
                return ResourceManager.GetString("NestedExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data loaded....
        /// </summary>
        internal static string NoDataLoadedMessage {
            get {
                return ResourceManager.GetString("NoDataLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color will be changed according to the configured style in case of an invalid numeric format or when the numeric value is outside of the configured boundaries (min: 1.0, max: 100.0). Maximum decimal places value equals 2..
        /// </summary>
        internal static string NumericValidationBehaviorDescription {
            get {
                return ResourceManager.GetString("NumericValidationBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes an Entry&apos;s text color when an invalid number is provided..
        /// </summary>
        internal static string NumericValidationShortDescription {
            get {
                return ResourceManager.GetString("NumericValidationShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RangeSlider is a slider with two thumbs allowing to select numeric ranges..
        /// </summary>
        internal static string RangeSliderDescription {
            get {
                return ResourceManager.GetString("RangeSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeSlider.
        /// </summary>
        internal static string RangeSliderTitle {
            get {
                return ResourceManager.GetString("RangeSliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SafeAreaEffect is an effect that can be added to any element through an attached property to indicate whether or not that element should take current safe areas into account. This is an area of the screen that is safe for all devices that use iOS 11 and greater. Specifically, it will help to make sure that content isn&apos;t clipped by rounded device corners, the home indicator, or the sensor housing on an iPhone X. The effect only targets iOS, meaning that on other platforms it does not do anything..
        /// </summary>
        internal static string SafeAreaLongDescription {
            get {
                return ResourceManager.GetString("SafeAreaLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SafeAreaEffect is an effectwill help to make sure that content isn&apos;t clipped by rounded device corners, the home indicator, or the sensor housing on an iPhone X..
        /// </summary>
        internal static string SafeAreaShortDescription {
            get {
                return ResourceManager.GetString("SafeAreaShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lower/Upper Thumb Size separately.
        /// </summary>
        internal static string SetLowerUpperThumb {
            get {
                return ResourceManager.GetString("SetLowerUpperThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lower/Upper Thumb Radius separately.
        /// </summary>
        internal static string SetLowerUpperThumbSeparately {
            get {
                return ResourceManager.GetString("SetLowerUpperThumbSeparately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shake.
        /// </summary>
        internal static string Shake {
            get {
                return ResourceManager.GetString("Shake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast.
        /// </summary>
        internal static string ShowSnackBarNoActionButton {
            get {
                return ResourceManager.GetString("ShowSnackBarNoActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SnackBar.
        /// </summary>
        internal static string ShowSnackBarWithActionButton {
            get {
                return ResourceManager.GetString("ShowSnackBarWithActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideMenuView is a simple and flexible Right/Left menu control..
        /// </summary>
        internal static string SideMenuViewDescription {
            get {
                return ResourceManager.GetString("SideMenuViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideMenuView.
        /// </summary>
        internal static string SideMenuViewTitle {
            get {
                return ResourceManager.GetString("SideMenuViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnackBar is closed by timeout.
        /// </summary>
        internal static string SnackBarIsClosedByTimeout {
            get {
                return ResourceManager.GetString("SnackBarIsClosedByTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnackBar is closed by user.
        /// </summary>
        internal static string SnackBarIsClosedByUser {
            get {
                return ResourceManager.GetString("SnackBarIsClosedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        internal static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort code.
        /// </summary>
        internal static string SortCode {
            get {
                return ResourceManager.GetString("SortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing is important, ok?! So this is where all of the tests for our little project reside..
        /// </summary>
        internal static string TestCasesDescription {
            get {
                return ResourceManager.GetString("TestCasesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Cases.
        /// </summary>
        internal static string TestCasesTitle {
            get {
                return ResourceManager.GetString("TestCasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Fade Animation.
        /// </summary>
        internal static string TestingFadeAnimation {
            get {
                return ResourceManager.GetString("TestingFadeAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb Border Color.
        /// </summary>
        internal static string ThumbBorderColor {
            get {
                return ResourceManager.GetString("ThumbBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb Color.
        /// </summary>
        internal static string ThumbColor {
            get {
                return ResourceManager.GetString("ThumbColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb Radius.
        /// </summary>
        internal static string ThumbRadius {
            get {
                return ResourceManager.GetString("ThumbRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb Size.
        /// </summary>
        internal static string ThumbSizeText {
            get {
                return ResourceManager.GetString("ThumbSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb.
        /// </summary>
        internal static string ThumbText {
            get {
                return ResourceManager.GetString("ThumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle SafeAreaEffect.
        /// </summary>
        internal static string ToggleSafeAreaEffect {
            get {
                return ResourceManager.GetString("ToggleSafeAreaEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Border Color.
        /// </summary>
        internal static string TrackBorderColor {
            get {
                return ResourceManager.GetString("TrackBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Color.
        /// </summary>
        internal static string TrackColor {
            get {
                return ResourceManager.GetString("TrackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Highlight Border Color.
        /// </summary>
        internal static string TrackHighlightBorderColor {
            get {
                return ResourceManager.GetString("TrackHighlightBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Highlight Color.
        /// </summary>
        internal static string TrackHighlightColor {
            get {
                return ResourceManager.GetString("TrackHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Size.
        /// </summary>
        internal static string TrackSize {
            get {
                return ResourceManager.GetString("TrackSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Thumb Border Color.
        /// </summary>
        internal static string UpperThumbBorderColor {
            get {
                return ResourceManager.GetString("UpperThumbBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Thumb Color.
        /// </summary>
        internal static string UpperThumbColor {
            get {
                return ResourceManager.GetString("UpperThumbColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Thumb Radius.
        /// </summary>
        internal static string UpperThumbRadius {
            get {
                return ResourceManager.GetString("UpperThumbRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Thumb Size.
        /// </summary>
        internal static string UpperThumbSize {
            get {
                return ResourceManager.GetString("UpperThumbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Thumb View Set.
        /// </summary>
        internal static string UpperThumbViewSet {
            get {
                return ResourceManager.GetString("UpperThumbViewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color will change accordingly to the style that is configured when a invalid URI is entered..
        /// </summary>
        internal static string UriValidationDescription {
            get {
                return ResourceManager.GetString("UriValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes an Entry&apos;s text color when an invalid URI is provided..
        /// </summary>
        internal static string UriValidationShortDescription {
            get {
                return ResourceManager.GetString("UriValidationShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This behavior waits for the user to stop typing and then executes a Command. The waiting threshold is adjustable, as well as there is an option to dismiss the keyboard after the user has stopped typing..
        /// </summary>
        internal static string UserStoppedTypingBehaviorDescription {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should dismiss keyboard automatically.
        /// </summary>
        internal static string UserStoppedTypingBehaviorDismissKeyboardOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorDismissKeyboardOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length threshold (number of characters).
        /// </summary>
        internal static string UserStoppedTypingBehaviorMinimumLengthThresholdOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorMinimumLengthThresholdOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching....
        /// </summary>
        internal static string UserStoppedTypingBehaviorSearchBarPlaceholderText {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorSearchBarPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed search for &apos;{0}&apos;.
        /// </summary>
        internal static string UserStoppedTypingBehaviorSearchResultLabelFormat {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorSearchResultLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This behavior waits for the user to stop typing and then executes a Command..
        /// </summary>
        internal static string UserStoppedTypingBehaviorShortDescription {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User stopped typing time threshold (in ms).
        /// </summary>
        internal static string UserStoppedTypingBehaviorTimeThresholdOptionLabel {
            get {
                return ResourceManager.GetString("UserStoppedTypingBehaviorTimeThresholdOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Label Spacing.
        /// </summary>
        internal static string ValueLabelSpacing {
            get {
                return ResourceManager.GetString("ValueLabelSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A custom view or control allows for adding custom functionality as if it came out of the Xamarin.Forms box..
        /// </summary>
        internal static string ViewsDescription {
            get {
                return ResourceManager.GetString("ViewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ViewsTitle {
            get {
                return ResourceManager.GetString("ViewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Corporation © 2020.
        /// </summary>
        internal static string WelcomeFooter {
            get {
                return ResourceManager.GetString("WelcomeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Extension.
        /// </summary>
        internal static string XAMLExtension {
            get {
                return ResourceManager.GetString("XAMLExtension", resourceCulture);
            }
        }
        
        internal static string RequiredStringValidationDescription {
            get {
                return ResourceManager.GetString("RequiredStringValidationDescription", resourceCulture);
            }
        }
        
        internal static string RequiredStringValidationShortDescription {
            get {
                return ResourceManager.GetString("RequiredStringValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string PasswordMatched {
            get {
                return ResourceManager.GetString("PasswordMatched", resourceCulture);
            }
        }

    }
}
