//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.CommunityToolkit.Sample.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.CommunityToolkit.Sample.Resx.AppResources.es", typeof(AppResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoDataLoadedMessage {
            get {
                return ResourceManager.GetString("NoDataLoadedMessage", resourceCulture);
            }
        }
        
        internal static string LoadingDataMessage {
            get {
                return ResourceManager.GetString("LoadingDataMessage", resourceCulture);
            }
        }
        
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string ItemTapped {
            get {
                return ResourceManager.GetString("ItemTapped", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string GratitudeMessage {
            get {
                return ResourceManager.GetString("GratitudeMessage", resourceCulture);
            }
        }
        
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string IntroductionTitle {
            get {
                return ResourceManager.GetString("IntroductionTitle", resourceCulture);
            }
        }
        
        internal static string IntroductionDescription {
            get {
                return ResourceManager.GetString("IntroductioDescription", resourceCulture);
            }
        }
        
        internal static string WelcomeFooter {
            get {
                return ResourceManager.GetString("WelcomeFooter", resourceCulture);
            }
        }
        
        internal static string BehaviorsTitle {
            get {
                return ResourceManager.GetString("BehaviorsTitle", resourceCulture);
            }
        }
        
        internal static string BehaviorsDescription {
            get {
                return ResourceManager.GetString("BehaviorsDescription", resourceCulture);
            }
        }
        
        internal static string AnimatioShortDescription {
            get {
                return ResourceManager.GetString("AnimatioShortDescription", resourceCulture);
            }
        }
        
        internal static string AnimationBehaviorTitle {
            get {
                return ResourceManager.GetString("AnimationBehaviorTitle", resourceCulture);
            }
        }
        
        internal static string TestingFadeAnimation {
            get {
                return ResourceManager.GetString("TestingFadeAnimation", resourceCulture);
            }
        }
        
        internal static string Shake {
            get {
                return ResourceManager.GetString("Shake", resourceCulture);
            }
        }
        
        internal static string EmailValidationDescription {
            get {
                return ResourceManager.GetString("EmailValidationDescription", resourceCulture);
            }
        }
        
        internal static string EmailValidationShortDescription {
            get {
                return ResourceManager.GetString("EmailValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string EventToCommandBehaviorDescription {
            get {
                return ResourceManager.GetString("EventToCommandBehaviorDescription", resourceCulture);
            }
        }
        
        internal static string EventToCommandShortDescription {
            get {
                return ResourceManager.GetString("EventToCommandShortDescription", resourceCulture);
            }
        }
        
        internal static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        internal static string NumericValidationShortDescription {
            get {
                return ResourceManager.GetString("NumericValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string NumericValidationBehaviorDescription {
            get {
                return ResourceManager.GetString("NumericValidationBehaviorDescription", resourceCulture);
            }
        }
        
        internal static string ConvertersTitle {
            get {
                return ResourceManager.GetString("ConvertersTitle", resourceCulture);
            }
        }
        
        internal static string ConvertersDescription {
            get {
                return ResourceManager.GetString("ConvertersDescription", resourceCulture);
            }
        }
        
        internal static string ItemTappedEventArgsShortDescription {
            get {
                return ResourceManager.GetString("ItemTappedEventArgsShortDescription", resourceCulture);
            }
        }
        
        internal static string ItemTappedSelectedEventArgsShortDescription {
            get {
                return ResourceManager.GetString("ItemTappedSelectedEventArgsShortDescription", resourceCulture);
            }
        }
        
        internal static string ByteArrayToImageSourceShortDescription {
            get {
                return ResourceManager.GetString("ByteArrayToImageSourceShortDescription", resourceCulture);
            }
        }
        
        internal static string ExtensionsTitle {
            get {
                return ResourceManager.GetString("ExtensionsTitle", resourceCulture);
            }
        }
        
        internal static string ExtensionsDescription {
            get {
                return ResourceManager.GetString("ExtensionsDescription", resourceCulture);
            }
        }
        
        internal static string TestCasesTitle {
            get {
                return ResourceManager.GetString("TestCasesTitle", resourceCulture);
            }
        }
        
        internal static string TestCasesDescription {
            get {
                return ResourceManager.GetString("TestCasesDescription", resourceCulture);
            }
        }
        
        internal static string ViewsTitle {
            get {
                return ResourceManager.GetString("ViewsTitle", resourceCulture);
            }
        }
        
        internal static string ViewsDescription {
            get {
                return ResourceManager.GetString("ViewsDescription", resourceCulture);
            }
        }
        
        internal static string AvatarViewTitle {
            get {
                return ResourceManager.GetString("AvatarViewTitle", resourceCulture);
            }
        }
        
        internal static string AvatarViewDescription {
            get {
                return ResourceManager.GetString("AvatarViewDescription", resourceCulture);
            }
        }
        
        internal static string AvatarViewSizeText {
            get {
                return ResourceManager.GetString("AvatarViewSizeText", resourceCulture);
            }
        }
        
        internal static string RangeSliderTitle {
            get {
                return ResourceManager.GetString("RangeSliderTitle", resourceCulture);
            }
        }
        
        internal static string RangeSliderDescription {
            get {
                return ResourceManager.GetString("RangeSliderDescription", resourceCulture);
            }
        }
        
        internal static string ThumbText {
            get {
                return ResourceManager.GetString("ThumbText", resourceCulture);
            }
        }
        
        internal static string ThumbSizeText {
            get {
                return ResourceManager.GetString("ThumbSizeText", resourceCulture);
            }
        }
        
        internal static string SetLowerUpperThumb {
            get {
                return ResourceManager.GetString("SetLowerUpperThumb", resourceCulture);
            }
        }
        
        internal static string LowerThumbSize {
            get {
                return ResourceManager.GetString("LowerThumbSize", resourceCulture);
            }
        }
        
        internal static string UpperThumbSize {
            get {
                return ResourceManager.GetString("UpperThumbSize", resourceCulture);
            }
        }
        
        internal static string ThumbColor {
            get {
                return ResourceManager.GetString("ThumbColor", resourceCulture);
            }
        }
        
        internal static string LowerThumbColor {
            get {
                return ResourceManager.GetString("LowerThumbColor", resourceCulture);
            }
        }
        
        internal static string UpperThumbColor {
            get {
                return ResourceManager.GetString("UpperThumbColor", resourceCulture);
            }
        }
        
        internal static string ThumbBorderColor {
            get {
                return ResourceManager.GetString("ThumbBorderColor", resourceCulture);
            }
        }
        
        internal static string LowerThumbBorderColor {
            get {
                return ResourceManager.GetString("LowerThumbBorderColor", resourceCulture);
            }
        }
        
        internal static string UpperThumbBorderColor {
            get {
                return ResourceManager.GetString("UpperThumbBorderColor", resourceCulture);
            }
        }
        
        internal static string LowerThumbViewSet {
            get {
                return ResourceManager.GetString("LowerThumbViewSet", resourceCulture);
            }
        }
        
        internal static string UpperThumbViewSet {
            get {
                return ResourceManager.GetString("UpperThumbViewSet", resourceCulture);
            }
        }
        
        internal static string ControlThumbsRadius {
            get {
                return ResourceManager.GetString("ControlThumbsRadius", resourceCulture);
            }
        }
        
        internal static string ThumbRadius {
            get {
                return ResourceManager.GetString("ThumbRadius", resourceCulture);
            }
        }
        
        internal static string SetLowerUpperThumbSeparately {
            get {
                return ResourceManager.GetString("SetLowerUpperThumbSeparately", resourceCulture);
            }
        }
        
        internal static string LowerThumbRadius {
            get {
                return ResourceManager.GetString("LowerThumbRadius", resourceCulture);
            }
        }
        
        internal static string UpperThumbRadius {
            get {
                return ResourceManager.GetString("UpperThumbRadius", resourceCulture);
            }
        }
        
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        internal static string TrackSize {
            get {
                return ResourceManager.GetString("TrackSize", resourceCulture);
            }
        }
        
        internal static string TrackColor {
            get {
                return ResourceManager.GetString("TrackColor", resourceCulture);
            }
        }
        
        internal static string TrackHighlightColor {
            get {
                return ResourceManager.GetString("TrackHighlightColor", resourceCulture);
            }
        }
        
        internal static string TrackBorderColor {
            get {
                return ResourceManager.GetString("TrackBorderColor", resourceCulture);
            }
        }
        
        internal static string TrackHighlightBorderColor {
            get {
                return ResourceManager.GetString("TrackHighlightBorderColor", resourceCulture);
            }
        }
        
        internal static string ControlTrackRadius {
            get {
                return ResourceManager.GetString("ControlTrackRadius", resourceCulture);
            }
        }
        
        internal static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        internal static string ValueLabelSpacing {
            get {
                return ResourceManager.GetString("ValueLabelSpacing", resourceCulture);
            }
        }
        
        internal static string SideMenuViewTitle {
            get {
                return ResourceManager.GetString("SideMenuViewTitle", resourceCulture);
            }
        }
        
        internal static string SideMenuViewDescription {
            get {
                return ResourceManager.GetString("SideMenuViewDescription", resourceCulture);
            }
        }
        
        internal static string MaskedDescription {
            get {
                return ResourceManager.GetString("MaskedDescription", resourceCulture);
            }
        }
        
        internal static string MaskedShortDescription {
            get {
                return ResourceManager.GetString("MaskedShortDescription", resourceCulture);
            }
        }
        
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        internal static string SortCode {
            get {
                return ResourceManager.GetString("SortCode", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string UriValidationDescription {
            get {
                return ResourceManager.GetString("UriValidationDescription", resourceCulture);
            }
        }
        
        internal static string UriValidationShortDescription {
            get {
                return ResourceManager.GetString("UriValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string MultiValidationDescription {
            get {
                return ResourceManager.GetString("MultiValidationDescription", resourceCulture);
            }
        }
        
        internal static string MultiValidationShortDescription {
            get {
                return ResourceManager.GetString("MultiValidationShortDescription", resourceCulture);
            }
        }
        
        internal static string MultiConverterDescription {
            get {
                return ResourceManager.GetString("MultiConverterDescription", resourceCulture);
            }
        }
        
        internal static string MultiConverterShortDescription {
            get {
                return ResourceManager.GetString("MultiConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string CameraViewTitle {
            get {
                return ResourceManager.GetString("CameraViewTitle", resourceCulture);
            }
        }
        
        internal static string CameraViewDescription {
            get {
                return ResourceManager.GetString("CameraViewDescription", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleZoom {
            get {
                return ResourceManager.GetString("CameraViewSampleZoom", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleSnapPicture {
            get {
                return ResourceManager.GetString("CameraViewSampleSnapPicture", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleStartRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStartRecording", resourceCulture);
            }
        }
        
        internal static string CameraViewSampleStopRecording {
            get {
                return ResourceManager.GetString("CameraViewSampleStopRecording", resourceCulture);
            }
        }
        
        internal static string ExpanderTitle {
            get {
                return ResourceManager.GetString("ExpanderTitle", resourceCulture);
            }
        }
        
        internal static string ExpanderDescription {
            get {
                return ResourceManager.GetString("ExpanderDescription", resourceCulture);
            }
        }
        
        internal static string NestedExpander {
            get {
                return ResourceManager.GetString("NestedExpander", resourceCulture);
            }
        }
        
        internal static string EnableNested {
            get {
                return ResourceManager.GetString("EnableNested", resourceCulture);
            }
        }
    }
}
